### ISSUE TITLE
Documentation improvement ideas

### ISSUE THREAD

**Issue by KevinColemanInc** [ankane/pgvector#2]
My friend and I were just chatting about adding vector search to pg the other day!

Could you add in the docs (or answer here?) these questions:

1. What algorithms are used to find the closest vectors? I see you mention FAIS, but its unclear exactly what was used.
2. Could you provide documentation on how this scales? Would this support 1B vectors?
3. Does this support partitioned indexes?

**Comment by ankane** [comment]
Hey @KevinColemanInc, glad to hear others are thinking about this.

1. It uses the IVFFlat index type. It doesn't use Faiss, but from what I can tell, Faiss invented the index type, which is why it's mentioned.
2. I haven't tried it with 1B vectors, but generally [product quantization](https://mccormickml.com/2017/10/13/product-quantizer-tutorial-part-1/) is used for that scale. I plan to add support if there's demand (#1).
3. Does this mean indexes on partitioned tables?

**Comment by KevinColemanInc** [comment]
2. about about 100M vectors?
3. I'm not asking a good question. nvm.
new question:
4. Does the index get backed up? like is it captured with `pg_dumps` and can be re-imported?

**Comment by ankane** [comment]
For 2: I've only tested with 1M at this point. From a storage perspective, it should have no problem storing any number of vectors up to the [Postgres limits](https://www.postgresql.org/docs/current/limits.html) ("limited by the number of tuples that can fit onto 4,294,967,295 pages"). From a performance perspective, you'll want to increase the number of inverted lists to keep queries fast (100 by default but supports up to 32,768).

For 4: It works like the other data and index types (works with `pg_dump`/`pg_restore`, uses WAL for recovery and replication)

**Comment by KevinColemanInc** [comment]
Awesome! Thanks for responding.
