### ISSUE TITLE
pgvector vs FAISS

### ISSUE THREAD

**Issue by KevinColemanInc** [ankane/pgvector#3]
update:
Upgrading to v0.1.1 and building with `PG_CFLAGS=-ffast-math make` reduced the query time to 2.2s! Big speed jump, but 1.7x slower than the FAISS / Python service.

-----
I imported 792010 rows of 512d image vectors (~5GB) (aka not random) and ran a tests[0] to find the 4 closests vectors to an exact vector in the dataset.

Searching with:
 - 1.279357709s - FAISS python web service (using json and IndexFlatL2) (with 791963 vectors [2]).
 - 11.381s - Searching (l2_distance) with pgvector extension (with 792010 rows) .

Hardware:
```
MacBook Pro (15-inch, 2018)
2.6 GHz 6-Core Intel Core i7
16 GB 2400 MHz DDR4
```

Importing took 11.381 seconds with the `COPY` cmd from a csv file with each row being the vector.

Any ideas why pgvector would be so much slower? The testing ENVs between the tools was significantly different, to the FAISS's dis-advantage, but FAISS was still much quicker.

[1] Not a "scientific" test. I had other programs running on the machine when running this test. Mileage may vary.
[2] The slight difference is the fais's vector import filters duplicate vectors.

**Comment by ankane** [comment]
Hey @KevinColemanInc, thanks for sharing the benchmark! pgvector will always have extra overhead since it needs to store more information than Faiss, but a few initial ideas for the big difference are:

1. Faiss uses SIMD to speed up distance calculations. This is on the list of things to try (#1).
2. From what I can tell, Faiss parallelizes IndexFlat search with OpenMP. I just released pgvector 0.1.1, which supports parallel queries. Use `EXPLAIN ANALYZE` to confirm it's working.
3. pgvector limits memory for queries to `work_mem`. Try different values like `SET work_mem = '6GB';` to see how that affects it.

**Comment by ankane** [comment]
It looks like you can enable automatic vectorization by compiling the extension with `PG_CFLAGS=-ffast-math make`, which sped things up in my testing.

**Comment by KevinColemanInc** [comment]
> Edit: Adding -march=native to PG_CFLAGS should also help.

This is related to building postgres, right? Or is this something related to the extension build?

**Comment by KevinColemanInc** [comment]
> Also, try ORDER BY vector_l2_squared_distance(a, b) instead of ORDER BY a <-> b, which will save a sqrt calculation for each comparison (the function is currently meant to be private, but may make sense to add a public version).

With v0.1.0, the time didn't change.

> Edit 2: Use SET max_parallel_workers_per_gather = 8; to increase the number of parallel workers (default is 2)

With v0.1.0, this may of shaved off ~400ms of the 11.1s, but im not sure.

**Comment by KevinColemanInc** [comment]
> It looks like you can enable automatic vectorization by compiling the extension with PG_CFLAGS=-ffast-math make, which sped things up in my testing.

Upgrading to v0.1.1 and building with `PG_CFLAGS=-ffast-math` reduced the query time to 2.2s! Big speed jump, but still slower than the FAISS / Python service.

**Comment by ankane** [comment]
Just merged a Makefile change to enable vectorization by default (5748cb6b4313d20d46b85a324d6535969c6e7bee).

I'm not aware of any other performance wins right now (but welcome contributions). Faiss will likely always be more performant since it can be more specialized, while pgvector can offer ACID compliance, replication, and filtering/joining with other attributes (all thanks to Postgres).

**Comment by KevinColemanInc** [comment]
Unfortunately I don’t know c/cpp so i wouldn’t be that effective.

I was really hoping to have the data resilience that ph offers. We gonna write our own command streak, disk persistence, and snapshoting, which pg would get for free.

Our data set is about 150GB of RAM, so speed is critical.

thanks for your help though. I’ll follow this repo to watch for changes.

**Comment by jkatz** [comment]
pgvector does not use FAISS.
